name: A

on:
  pull_request:
    branches: master

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: AB
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          sleep 10
          for i in {1..10}; do
            curl -s -o info \
                      -H "Accept: application/vnd.github.v3+json" \
                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      ${{ github.api_url }}/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}
          done
      - name: info
        run: |
            curl -s \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}
