name: A

on:
  pull_request:
    branches: master

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: AB
        run: |
          curl \
                      -H "Accept: application/vnd.github.v3+json" \
                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      ${{ github.api_url }}/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}
