name: A

on:
  pull_request:
    branches: master
  
  schedule: 
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: AB
        run: echo 'Hello'
