name: Release Test

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'version name'
        required: true
        default: '12.24'
      startDate:
        description: 'start date'
        required: true
        default: '2021-05-01'
        
        
jobs:
  master2release:  
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo ${{ github.event.inputs.versionName }}
          echo ${{ github.event.inputs.startDate }}
        
