name: Release Test

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'version name'
        required: true
        default: '12.24'
      startDate:
        description: 'start date'
        required: true
        default: '[2 weeks past]'
        
jobs:
  master2release:  
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo ${{ github.event.inputs.versionName }}
          
          if [[ ${{ github.event.inputs.startDate }} == '[2 weeks past]' ]]
          then
            github.event.inputs.startDate = $(date -v-2w +%F)
          fi
          
          echo ${{ github.event.inputs.startDate }}
        
