name: joined

on: push

jobs: 
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
    
      - name: call 1
        uses: ./.github/workflows/a
      - uses: ./.github/workflows/b
        name: call2
      #- name: call 1
        #uses: ./.github/actions/Test_Action
      #  uses: ./.github/actions/test1
        
      #- name: call 2
      #  uses: ./.github/actions/job1

            #      - name: cat
            #run: gh workflow run ./.github/actions/test_action.yml
