name: joined

on:
  push:
  #workflow_dispatch:
  #schedule:
  #  - cron: '* * * * *'

jobs: 
  combine:
    runs-on: ubuntu-latest
    steps:
    
      - name: Hello
        run: |
          echo 'Hello'
          echo ${{ secrets.GITHUB_TOKEN }}
      - name: url
        run: |
            echo "PR_URL=https://github.com/${GITHUB_REPOSITORY}/pull/${{github.event.pull_request.number}}"
            
      - name: FAIL
        run: echo failed && exit 1
            
      #- name: checkout
      #  uses: actions/checkout@v2.3.4
      #  with:
      #    ref: ${{ github.head_ref }}
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    submodules: recursive
    
      #- name: call 1
        #uses: ./.github/actions/Test_Action
      #  uses: ./.github/actions/test1
        
      #- name: call 2
      #  uses: ./.github/actions/job1

            #      - name: cat
            #run: gh workflow run ./.github/actions/test_action.yml
