name: joined

on: push

jobs: 
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
    
      - name: call 1
        uses: ./.github/workflows/test_action.yml
        
        
      - name: call 2
        uses: ./.github/workflows/test_2.yml
