name: test_2

on:
  workflow_run:
    workflows: ["joined"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: j_1
        run: echo j_1
