name: Test Action
on:
  push:
    branches: [master]

jobs:
  test1:
    runs-on: ubuntu-latest 
    steps:
      - name: Echo something
        run: echo 'something'; echo $GITHUB_ENV; echo ${GITHUB_REF##*/}


