name: Test_Action
on:
  workflow_run:
    workflows: ["joined"]
    types:
      - completed

jobs:
  test1:
    runs-on: ubuntu-latest 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Echo something
        run: echo 'something'; echo $GITHUB_ENV; echo ${GITHUB_REF##*/}


