name: Test_Action
on:
  workflow_run:
    workflows: ["joined"]
    types:
      - completed

jobs:
  test1:
    runs-on: ubuntu-latest 
    steps:
      - name: Echo something
        run: echo 'something'; echo $GITHUB_ENV; echo ${GITHUB_REF##*/}


